language: python
python:
  - "2.7"

sudo: false

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run -t clean
  - patch/patch.sh
  - export RELEASE_VERSION=$(git describe --tags --always)
  - platformio run
  - export FIRMWARE=.pioenvs/prod/LaCOOLBoard-${RELEASE_VERSION}.bin
  - mv .pioenvs/prod/firmware.bin ${FIRMWARE}
notifications:
  email:
    on_success: build@lacool.co
    on_failure: build@lacool.co
  slack:
    secure: TxKrv7J+fHDe98JOmzKve1PLvmuTdK4/wzSKQx7vOIz4tyje+CQuFJMPOOvjkaJoS8jT+s0FR25q8r5QF1mFpIofBPvvLu/PL3KOaPDs2lE4HXHoQi4vZiCQnDJbpQhk4dxwLHqbQ/OHwZOm0qmVusB9EJjf81iTxr2jA09/neEtPE06Yn3FIU+XaxJYbI7VeN5SgOeOCroo931BvYjyEcUhMUuqVHPI5KuBkNJ1bc3fAQyg6KGi5jFs18Fugd6OZQGMV8aJf4l9weyTUXL60x9i6AUOoCSNb+pMAQYfG/bn7PWhQgsV8q+hB5cNESRpklNA6c4uLDWsdCb1/gI0NtNDdwg8oEmRpRJXf5W9/cCzWZFHrruFJm12wjNaSAy63a8bOF15Ve79ngGrUGHwSDjXA5JSeYrtvNVM9e4IWfmjcNK2JeXnhhnicAAPXPmxLLlyTtTsDWcmYy3b7rWcRmwzmRW2NCoQGctw2VndXOqk5ojl7iZSdNYI7JkeX9cLU4YfJPbnb2qviuENrvl14D/2hv4jozFGTd/6A8Z6Xs/qQxknfKrbS0BN4haA9X6hRPO0gs5qfMh4UrVM/wJ7N4tcWR/F4C6tkxdmH+tfAVTYLAnuhZRfqFhqxI5Ni50iWNYzFeweH3jZ/2CgYTeyj3Tj/BN27ityKjL76mZEzMc=
deploy:
  skip_cleanup: true
  provider: releases
  file: "${FIRMWARE}"
  api_key:
    secure: rKQbtn2MgGMKqlc85hng89PcjDoU2H+lsIcXXTb56inOWUzINhtR+Uxjvixk9U5yNjX/KUYLzcZYWyxvybv0qlW7ZRH5LJsK0F/RFMp4t7u7IG/OCHjpixbLM3hlWynrraX1XULPbvM3UDpnGa8yzFt0oLk1pBaU85G91UAwRQOb5ZE/LcG+P5ZxrQLWzVxW8ezE6d1201/gDjeIyTlfRnL26k1rtkk+znVtCtBncuPRxfNGJyBX4Es2XzOgx8YQQAnQFp0eHYYsetOn/d3h3AbClNI8mG6p6sy3k/z1EhO3CCWypfEWuZ2wwopMDEA//Py+BoIZ4BLws0LwVbjI+dznfcexsXtCIAWHxEqiqqLQsQFxxk7L1hFa1m4aQjS6AGpy3rvJx+uQOPrcdP+749wjsxzIfp0eQgi4TcASI2AVtJPw/x0MyPerrlusf7mOhSdz+WC+M4AjSUoYGQzejFaWNZbDkDgYebrxqAcTHiHc2PVSjbLtAtM9FTtjRoMUF7Ys2jsHDpcfIGzT6pBFUHh3MotQAfB9oH/OvsNu5EB56lLdHsSl9sHfZNz5wLNbXcqW1sW9JlvFnDC8/t60WXv+lPBn1QI6DBA8kCTuO3HRRiFwVxTSe4T90Pep56sg+ALwBO8obER3JCNIGSh61BxM/TIV1s2oRYAp6wpxiOs=
  name: La COOL Board ${RELEASE_VERSION}
  file_glob: true
  on:
    repo: LaCoolCo/LaCOOLBoard
    tags: true
